# Generated by Django 4.2.6 on 2023-11-14 19:28

import autoslug.fields
import colorfield.fields
from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Ürün Kategori')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Ürün rengi')),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Cinsiyet')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Ürün Resmi İsmi')),
                ('image', models.FileField(upload_to=main_app.models.generate_filename, verbose_name='Ürün resmi')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='Ürün Bedenli')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Ürün Başlığı')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('price', models.PositiveIntegerField(verbose_name='Ürün Fiyatı')),
                ('description', models.TextField(verbose_name='Ürün Açıklaması')),
                ('is_active', models.BooleanField(default=True, verbose_name='ürün aktifmi')),
                ('categories', models.ManyToManyField(related_name='productcategory', to='main_app.categories', verbose_name='Kategori')),
                ('color', models.ManyToManyField(to='main_app.color', verbose_name='Renk')),
                ('gender', models.ManyToManyField(to='main_app.gender', verbose_name='Cİnsiyet')),
                ('image', models.ManyToManyField(blank=True, to='main_app.image', verbose_name='Ürün Resmi')),
                ('size', models.ManyToManyField(to='main_app.size', verbose_name='Beden')),
            ],
        ),
    ]
